version: '3.7'

services:
  habsang:
    build: ./server-kuangin
    environment:
      - CUDA_VISIBLE_DEVICES=all
      # - FORCE_CPU=True
    ports:
      - "5000:5000"
    volumes:
      - "./camsu/hparams.py:/WaveRNN/hparams.py:ro"
      - "./camsu/text_init.py:/WaveRNN/utils/text/__init__.py:ro"
      - "./camsu/text_symbols.py:/WaveRNN/utils/text/symbols.py:ro"
      - "./4-ciidien-20190516-16k-MeuLid-checkpoints:/WaveRNN/checkpoints"
      - "./6-giedgo:/giedgo"
    restart: always
